### ISSUE TITLE
Homework #1 announced?

### ISSUE THREAD

**Issue by Fathachmad** [swtv-kaist/cs492-fall23#1]
In one of the older slide there is an announcement about the homework with the deadline being on 21st of September. Is it still the case? As far as I remember, there isnt any announcement of homework yesterday

**Comment by swtv-kaist** [comment]
Please ignore the HW page in the outdated slides.  
Sorry for the unnecessary confusion.

I have uploaded correct slides now 
(sorry that my previous push of the updated slides did not work...)
