### ISSUE TITLE
HPW#2, high priority of writer trace

### ISSUE THREAD

**Issue by Fathachmad** [swtv-kaist/cs492-fall23#10]
I am struggling to find what made the given design_rw:
proc R1 =     'lock.ir1.	
      (   'zero_WW.	
	  ('zero_AW.'inc_AR.'unlock.READ1	
	      + 'non_zero_AW.'inc_sleep.'unlock.R1')	
	  + 'non_zero_WW.'inc_sleep.'unlock.R1') 
proc R1' =     wake_up.'lock.	
      (   'zero_WW.	
	  ('zero_AW.'inc_AR.'unlock.READ1	
	      + 'non_zero_AW.'inc_sleep.'unlock.R1')	
	  + 'non_zero_WW.'inc_sleep.'unlock.R1') 

proc R2 =    'lock.ir2.	
     (   'zero_WW.	
	 ('zero_AW.'inc_AR.'unlock.READ2	
	     + 'non_zero_AW.'inc_sleep.'unlock.R2')	
	 + 'non_zero_WW.'inc_sleep.'unlock.R2') 
proc R2' =     wake_up.'lock.	
      (   'zero_WW.	
	  ('zero_AW.'inc_AR.'unlock.READ2
	      + 'non_zero_AW.'inc_sleep.'unlock.R2')	
	  + 'non_zero_WW.'inc_sleep.'unlock.R2') 

proc W =    'lock.ww.'inc_WW.	
    ( 'zero_AR.	
	('zero_AW.'dec_WW.'inc_AW.'unlock.WRITE	
	    +'non_zero_AW.'inc_sleep.'unlock.W')	
	+ 'non_zero_AR.'inc_sleep.'unlock.W') 
proc W' =     wake_up.'lock.	
      ( 'zero_AR.	
	  ('zero_AW.'dec_WW.'inc_AW.'unlock.WRITE	
	      +'non_zero_AW.'inc_sleep.'unlock.W')	
	  + 'non_zero_AR.'inc_sleep.'unlock.W')

ensures the high priority of writer. I think it might still allow for trace `ir1.ww.rs1` in the design. can you clarify?

**Comment by ahcheongL** [comment]
The design allows ``ir1.ww.rs1``, and the requirement of HPW#2 also does.

**Comment by Fathachmad** [comment]
in that case, both the requirement and the design does not ensure the high priority of writer?

**Comment by ahcheongL** [comment]
It is hard to say so, there can be diverse interpretations of the natural word "high priority".
The design and the requirement of HPW#2 do not allow ``ww.ir1.rs1``.
You need to understand the subtle difference between HPW#1 and HPW#2.

**Comment by Fathachmad** [comment]
I think i kind of understand, thank you for clarifying
