### ISSUE TITLE
#3 of HW1

### ISSUE THREAD

**Issue by woojinnn** [swtv-kaist/cs492-fall23#11]
Sorry, but I cannot express what I wanted to say in English well... Let me use Korean.
HPR에서 `ir1.ww.ir2.rs1.re1.ws`는 허용된 trace라고 보면 될까요?
큐에 들어온 순서는 `ir1 -> ww -> ir2`이고, ir1이 read를 마친 다음 큐에서 나갔다면, 큐에서의 순서는 `ww -> ir2`가 됩니다. 이 경우, `ww`가 `ir2`보다 먼저 들어왔다고 생각해서 `ws`를 시작할 수 있다고 생각했는데, 맞게 생각한 걸까요?

**Comment by ahcheongL** [comment]
Yes, it is allowed.

**Comment by woojinnn** [comment]
thank you!
