### ISSUE TITLE
modelling prince of persia puzzle

### ISSUE THREAD

**Issue by Fathachmad** [swtv-kaist/cs492-fall23#13]
is it alright if we get clue to how we can model the state in the 2nd question of HW 2 (the prince of persia puzzle)? I have trouble imagining how we can put them into state-like condition, especially since their positional information is very important to the puzzle

**Comment by ahcheongL** [comment]
I'm sorry, I don't get the point you are having trouble with.

**Comment by Fathachmad** [comment]
compared to question 1 and 3 where we have clear representation of state (1 being the position of the 3 entities and 3 being the trace of signal) it is a bit difficult to represent the state in question 2. I can only imagine representing them in matrices as the positional information of each block is important. i am asking if there are better way to represent them or can you give us guidance to represent such matrices in promela.

**Comment by swtv-kaist** [comment]
Your job in HW#2 is to model system states.  For an example of Q2, a state may consist of the directions of the 4 handles.  But you should specify the goal constraint (i.e., a route from a source to a sink through some of R1~R11)
