### ISSUE TITLE
HW3: Need of Clarifications

### ISSUE THREAD

**Issue by yheechan** [swtv-kaist/cs492-fall23#14]
The requirements of `buggy_max_heapify` states that "it should make a subtree whose root is x[i] a max heap".

As I know, a tree or subtree is max_heap if the the root value is the maximum value.

Does the written requirement refer to executing `buggy_max_heapify` iteratively from the leaf node to the target node?

My confusion comes from this example.
Stage 1:
<img width="839" alt="Screenshot 2023-12-05 at 5 42 19 PM" src="https://github.com/swtv-kaist/cs492-fall23/assets/50125642/d9566dcc-6a71-48f0-83e8-837b0aa0cabd">

Stage 2:
<img width="839" alt="Screenshot 2023-12-05 at 5 42 31 PM" src="https://github.com/swtv-kaist/cs492-fall23/assets/50125642/c35a989c-23b4-486f-ae39-2dff3803bdc4">

As seen in the these two stages.
Executing a single `max_heapify(x, 2, h_size)` command (on index 2),
it doesn't not make x[2] a full max_heap.
The subtree on the right child is not a **max_heap**.

**Comment by swtv-kaist** [comment]
Would you read "Assumptions" in the page 2 of HW#3 carefully?
-  "2. The right and left sub-trees of node i are maxh eaps, but that x[i] maybe smaller than its children"

**Comment by yheechan** [comment]
I have finally understood the meaning of assumption.
Thank you.
