### ISSUE TITLE
counteraction in HW3 Q1

### ISSUE THREAD

**Issue by Fathachmad** [swtv-kaist/cs492-fall23#15]
I am sorry for the possibly basic question, but I needed to make sure. In the Q1 we needed to show the counterexample to prove that the problem is solvable, so I assumed that we will be needing to use the --trace command. However, I find that cbmc wasnt able to find the counterexample even after 100k+ iteration. I tried using the hanoi3.c from the lecture slide and the same result occurs (in which it couldnt find the counterexample from --trace command). Hence, which command that we are supposed to be using? I think --unwind can be a possible answer but I am asking just to make sure.

**Comment by ahcheongL** [comment]
Try running `cbmc hanoi.c --unwind 7`.
You will get an assertion failure result.
You can get the trace by adding `--trace` option.

**Comment by Fathachmad** [comment]
thank you!
