### ISSUE TITLE
[CCS] Questions on the reader-writer system

### ISSUE THREAD

**Issue by jaehyun1ee** [swtv-kaist/cs492-fall23#2]
Hi, I have two questions regarding the reader-writer’s formal requirement specification.

Unfortunately I cannot attend classes this week due to an academic trip, so my understanding is based on the rw.pdf paper and the lecture notes in this class repository.

<img width="516" alt="Pasted Graphic" src="https://github.com/swtv-kaist/cs492-fall23/assets/44872014/c33bb1e0-618e-4ed2-a054-d18ffd34180e">

The figure above is the finite state machine constructed by enumerating all valid execution paths satisfying properties CON, EW, HPW, and CEO.

**Q1. Number of states in the diagram**

I believe the states in the diagram are defined as, s = (n_ir1, n_rs1, n_ir2, n_rs2, n_ww, n_ws).

To my understanding, the n_event means, the number of “active” event.
CEO (correct event ordering) in the lecture slide requires that,
```
n_ir(s_i) >= 0 /\ n_rs1(s_i) >= 0 /\ n_ir(s_i) + n_rs1(s_i) <= 1
n_ir(s_i) >= 0 /\ n_rs1(s_i) >= 0 /\ n_ir(s_i) + n_rs1(s_i) <= 1
n_ir(s_i) >= 0 /\ n_rs1(s_i) >= 0 /\ n_ir(s_i) + n_rs1(s_i) <= 1
```

Considering only reader 1, (n_ir1, n_rs1) is one of (0, 0), (1, 0), or (0, 1). ((1, 1) is not allowed.) The same applies for reader 2 and writer, so there should be AT MOST 3 * 3 * 3 = 27 states in the system.
But the given diagram has 34 states, which confuses me at the moment.

So, are the states in the diagram defined differently than s = (n_ir1, n_rs1, n_ir2, n_rs2, n_ww, n_ws)?

**Q2. How does HPW (high priority of writer) work in the diagram?**

I have marked two execution paths in the diagram as yellow and green.

Node b2 at the yellow path should have state (1, 0, 0, 0, 1, 0) and node 21 at the green path should also have state (1, 0, 0, 0, 1, 0). 
The two nodes are the same with regards to their states.
I wonder why they are not collapsed into a single node in the diagram.

And yes, the two nodes differ in their next branching. Node b2 allows event rs1 (node b2 to b12), while node 21 doesn’t. 
I think it is because for node b2, reader 1 came BEFORE the writer and for node 21, reader 1 came AFTER the writer.

But I wonder how HPW property below makes such difference.
```
(n_ww(s_i) = 1 /\ n_rs1(s_i) = 0 /\ n_rs2(s_i) = 0) -> (n_rs1(s_i+1) = 0 /\ n_rs2(s_i+1) = 0)
```

I think such property should restrict node b2 from taking event rs1, which is allowed in the diagram.

Or, is it just okay because we only want may preorder of the system design against the requirement diagram? (in CWNC command, `le -S may Sys Spec`)

**Comment by ahcheongL** [comment]
Hello, this is TA
1. The state transition graph is not minimized version, you can theoretically represent all required states in s = (n_ir1, n_rs1, n_ir2, n_rs2, n_ww, n_ws), but there are some "duplicate" state in the graph diagram.
For example, a state reached by 0->ir1->ww->ir2 and another state 0->ir2->ww->ir1 is shown as seperate one, but actually I think you can consider them as same ones.(The yellow and green ones are also an example pair).
(You can refer [DFA_minimization](https://en.wikipedia.org/wiki/DFA_minimization).)
I think the graph diagram is not minimized to make it more easy to read.
2. I'm not sure whether HPW is properly specified in the graph.
I assumed HPW was not stated in the specification and the graph when I made a model solution, 
but I need double check with the professor.

**Comment by swtv-kaist** [comment]
Hi, Jaehyun.

Thank you for the questions.   
As TA mentioned, the requirement LTS for 2R1W in the slides is not a minimized one and it has a bug ;-(
(e.g., b2-rs1->b12 should NOT be allowed)  
I will fix it and upload correct slides.

Thanks
-Moonzoo

**Comment by jaehyun1ee** [comment]
Thank you for the clarifications :)
