### ISSUE TITLE
Buf2

### ISSUE THREAD

**Issue by woojinnn** [swtv-kaist/cs492-fall23#3]
I am reviewing Boolean buffer of size 2.
We learned that its CCS can be designed like below:
```
proc Buf2   =  in0.Buf2_0 + in1.Buf2_1

proc Buf2_0  = out0.Buf2 +	 
         in0.Buf2_00 + in1.Buf2_01

proc Buf2_1   = out1.Buf2 +	  		    
         in0.Buf2_10 + in1.Buf2_11

proc Buf2_00 = out0.Buf2_0
proc Buf2_01 = out0.Buf2_1
proc Buf2_10 = out1.Buf2_0
proc Buf2_11 = out1.Buf2_1
```
Here, `out0` means "0 is going out as output". I wonder why that specification doesn't mark quote to indicate it is output action(I mean, `'out0`). Is it because there is no component that receive the output of `out0`?

**Comment by swtv-kaist** [comment]
Oops, I forgot to answer this question.  Sorry.  

It is recommendable, but not mandatory to put a quote to an action ```a``` to indicate that ```a``` is an output.  
When you put a quote to an action, you implicitly mean that a system may have a corresponding co-name action to make communication w/ the action.

Also, input/output distinction may not be important depending on your system abstraction level.
(see that traditional automata theory does not distinguish input/output)
