### ISSUE TITLE
τ in parallel composition

### ISSUE THREAD

**Issue by Fathachmad** [swtv-kaist/cs492-fall23#4]
i am reviewing τ in parallel composition and find a confusion. according to this rule:
![1](https://github.com/swtv-kaist/cs492-fall23/assets/79952761/662fe7c4-e637-4ca6-aad0-b896eb1e690d)
shouldnt τ be (or atleast include) the line from buf=buf1|buf2 to comm'.buf1|out.buf2 in this lts:
![2](https://github.com/swtv-kaist/cs492-fall23/assets/79952761/00d5d618-d936-48ac-8ce5-8623050b59f3)
I find it confusing because the definition of τ itself is a bit vague (internal hidden action) and can be interpreted in lot of ways

**Comment by ahcheongL** [comment]
You can think of τ to represent inter-process signaling.
Here, we have 4 actions, in, out, comm, and comm'.
in and out are external actions that are given outside of the buffer.
comm and comm' are internal actions (inter-process signals that are performed by two processes, for example, (comm'.Buf1 | comm.out.Buf2), we are running two processes, comm'.Buf1 and comm.out.Buf2 concurrently.).

So, τ represents only comm and comm' pair here.

Buf = (in.comm'.Buf1 | comm.out.Buf2)
Buf - in -> (comm'.Buf1 | comm.out.Buf2) - comm -> (comm'.Buf1 | out.Buf2 )
Here, we need two actions (in and comm), and they are not corresponding internal actions.

**Comment by Fathachmad** [comment]
I see, does that means the action τ is the same as performing both comm and comm' concurrently, hence the change of state from comm'.buf1|comm.out.buf2 to buf1|out.buf2 ?

**Comment by ahcheongL** [comment]
Yes

**Comment by Fathachmad** [comment]
then how do we differentiate between internal and external action again? im not sure if i get the good idea from the example why comm and comm' is considered an internal action

**Comment by swtv-kaist** [comment]
> how do we differentiate between internal and external action again? 

If an action ```a``` is restricted by \ operator in a target system, you can think ```a``` is an internal action, since you cannot observe ```a``` from outside of the target system.

**Comment by Fathachmad** [comment]
however in the example above, i dont think its specified that comm are restricted - as it was on the slide before restriction rule are introduced - i was wondering if we can take comm as internal action because it is present in both process buf1 and buf2

**Comment by ahcheongL** [comment]
The concept of restriction first appeared in the next slide to "fix" the diagram.

**Comment by Fathachmad** [comment]
I see, then can i take that internal action will be explicitly described for every system using the restriction rule?

**Comment by swtv-kaist** [comment]
Well, your cause-result reasoning seems not sound. 

No action is inheretently internal or external; it depends on system abstraction/refinement level.  
An action ```a``` is an external action in S1.  But ```a``` can be an internal action in S2 which contains S1 with \ \{```a```\}.

**Comment by Fathachmad** [comment]
so that means if there were internal action, then it would be described - although not every system are guaranteed to have an internal action?

**Comment by swtv-kaist** [comment]
Would you explain your question in detail?  I am sorry that I may not understand your question correctly.

**Comment by Fathachmad** [comment]
I guess my question come down to how we can differentiate between internal and external action. That is why I asked if we can assume every action described by the restriction rule to be an internal action
