### ISSUE TITLE
CCS linter

### ISSUE THREAD

**Issue by woojinnn** [swtv-kaist/cs492-fall23#5]
I made a CCS linter extension which is available in the VSCode.
Take a look if you want!
https://github.com/woojinnn/ccs_linter

It's quite simple now, but I hope some of you may contribute to enhance its functionality!
What I considered until now is, keyword(`proc` and `set`), and comment(starts with `*`)
If you want, take a look at `<ccs_linter>/syntaxes/ccs.tmLanguage.json` file.
Hope this helps you :)

Sample output:
![image](https://github.com/swtv-kaist/cs492-fall23/assets/52380072/094523ea-206d-4c97-889b-071cb6546bbb)

**Comment by ahcheongL** [comment]
Thank you for the sharing :)

**Comment by swtv-kaist** [comment]
Wow, thank you very much for your talent donation.
I put a link to your CCS linter at CS492B home page ;-)
