### ISSUE TITLE
Question about HPW

### ISSUE THREAD

**Issue by woojinnn** [swtv-kaist/cs492-fall23#6]
I have a question about the definition of HPW. Specifically, I want to make sure what action is indicated.
1. "While no reader is reading the CDA" -> I understood it as `n_rs1 == 0 && n_rs2==0`. Am I correct?
2. "If a writer has tried to write" -> Does this mean `ww` or `ws`?
3. "No reader is waiting to read CDA" -> I understood it as `ir{1,2}` happened in the earlier trace.
4. "No reader should read CDA after T" -> I understood it as `rs` cannot happen. Am I correct?
5. "Until the writer completes writing" -> I understood it as `we` occurs.

**Comment by ahcheongL** [comment]
1. "While no reader is reading the CDA" -> I think, yes
2. "If a writer has tried to write" -> ww
3. "No reader is waiting to read CDA" -> ir{1,2} *not* happened in the earlier trace.
4. "No reader should read CDA after T" -> rs can not happen.
5. "Until the writer completes writing" -> until we happens.

**Comment by woojinnn** [comment]
Thanks!
