### ISSUE TITLE
Question about HPW#1

### ISSUE THREAD

**Issue by woojinnn** [swtv-kaist/cs492-fall23#7]
I think the difference between HPW#1 and HPW#2 is whether we distinguish `ww.rs1` and `rs1.ww` or not. (More generally, whether the order in the trace matter). While HPW#2 has to distinguish the order, HPW#1 doesn't have to.

I have a question about state transition diagram in slide 11 of "lec26-rw-example-v12.pdf" file. (I attached a figure below)
If we don't have to distinguish between the order inside the trace, I think state `21` and state `b2` are identical. Then, is there any reason that the diagram is drawn as if it separate them?

![image](https://github.com/swtv-kaist/cs492-fall23/assets/52380072/58fbafa0-50fe-4bad-91ae-d66eb2d9c957)

**Comment by ahcheongL** [comment]
1. HPW#2 distinguish them, so it would be easier to compare HPW#1 and HPW#2 using the diagram above.
2. There are multiple "duplicate" nodes here, if we merge them, the graph looks much more complicated, I guess. (Much more edges will cross each other)

**Comment by woojinnn** [comment]
Thank you for quick and clear response!
