### ISSUE TITLE
Is internal action tau bound to specific action(or label)?

### ISSUE THREAD

**Issue by YoungseokCh** [swtv-kaist/cs492-fall23#8]
In short, I wonder whether $\tau$ is bound to specific action $\alpha$.
Suppose we have the system below:
$$\text{Sys} = a.A0 | a'.A1 | b.B0 | b'.B1$$
Then, is it correct to state
$$\text{Sys} \xrightarrow{\tau} A0 | A1 | B0 | B1$$
? It's based on the parallel composition rule that $\tau$ can represent the transitions $a, a'$ and $b, b'$.

If it's not, what is the next state when $\tau$ is applied to $\text{Sys}$?

**Comment by ahcheongL** [comment]
$\tau$ can be either (a,a') or (b, b').

$$\text{Sys} = (a.A0 | a'A1 | b.B0 | b'.B1) \backslash \\{a, b\\} $$

$$\text{Sys} \xrightarrow{\tau} (a.A0 | a'.A1 | B0 | B1) \xrightarrow{\tau} (A0|A1|B0|B1)$$

or

$$\text{Sys} \xrightarrow{\tau} (A0 | A1 | b.B0 | b'.B1) \xrightarrow{\tau} (A0|A1|B0|B1)$$

**Comment by YoungseokCh** [comment]
Thank you! So, $\tau$ is either $(a, a')$ or $(b, b')$, not both. Maybe writing $\tau$ as $\tau_a$, $\tau_b$ can be more rigourous..

**Comment by swtv-kaist** [comment]
> Maybe writing  as $\tau_a$, $\tau_b$ can be more rigourous.

Well, $\tau$ is carefully designed to hide/abstract which two actions makes communication.  By removing such information, $\tau$, an internal hidden action, can truly hide system's inner behavior which should be abstracted out to reduce complexity.

**Comment by YoungseokCh** [comment]
I was confused because the state transition $\xrightarrow{a}$ is not a function from state to state. If action is $\tau$, the next state can have multiple options.

After having some thoughts, I also realized that many rules are non-deterministic, especially for compositions:

$$
a.E + a.F \xrightarrow{a} ?
$$

In this case, the next state can be either $E$ or $F$.

Based on these observations, I concluded that given action $a$, the state transition $\xrightarrow{a}$ is just a relation, not a function that next state is determined by current state.

**Comment by swtv-kaist** [comment]
> the state transition  is just a relation, not a function that next state is determined by current state.

You are right.  CCS rules allow non-deterministic behaviors of a process to describe a complex system in an abstract way.
