### ISSUE TITLE
HPW2 valid trace

### ISSUE THREAD

**Issue by woojinnn** [swtv-kaist/cs492-fall23#9]
I have a question about HPW#2. Let's just consider 1 reader and 1 writer system.
What requirement makes `ir.ww.rs.ws` an invalid trace? I think WE(exclusive write) makes `ir.ww.ws.rs` impossible, but I cannot find what rule makes `ir.ww.rs.ws` invalid.

**Comment by ahcheongL** [comment]
Exclusive writing makes ``ir.ww.rs.ws`` also invalid.

**Comment by woojinnn** [comment]
Oh I see. Thank you!
